elements = {
    "Jobs_bage": ["XPATH", '//*[@id="navbarText"]/ul/li[2]/a/span'],
    "workers_bage": ["XPATH", '//*[@id="navbarText"]/ul/li[1]/a/span'],
    "jobs_table": ["XPATH", '//*[@id="sapper"]/main/div/div/div/div[3]/div/div/table'],
    "summary_table": ["XPATH", '//*[@id="sapper"]/main/div/div/div/div[2]/div/table'],
    "ALL_filter": ["XPATH", "//button[contains(.,'All')]"],
    "Success_filter": ["XPATH", "//button[contains(.,'Success')]"],
    "Failure_filter": ["XPATH", "//button[contains(.,'Failure')]"],
    "New_filter": ["XPATH", "//button[contains(.,'New')]"],
    "Running_filter": ["XPATH", "//button[contains(.,'Running')]"],
    "Waiting_filter": ["XPATH", "//button[contains(.,'Waiting')]"],
    "Halted_filter": ["XPATH", "//button[contains(.,'Halted')]"],
    "no_jobs": ["XPATH", '//*[@id="sapper"]/main/div/div/div/div[3]/div/div'],
    "no_workers": ["XPATH", '//*[@id="sapper"]/main/div/div/div/div[3]/h2'],
    "workers_table": ["XPATH", "//*[@id='sapper']/main/div/div/div/div[3]/div/div/table"],
    "alert_home": ["XPATH", "//*[@id='navbarText']/ul/li/a"],
    "alerts_table": ["XPATH", "//*[@id='sapper']/main/div/div[4]/div/div/div/div/table"],
    "alerta_search_box": ["ID", "InputSearch"],
    "All_filter_alerta": ["ID", "pills-all-tab"],
    "Production": ["ID", "pills-production-tab"],
    "Staging": ["ID", "pills-staging-tab"],
    "Development": ["ID", "pills-development-tab"],
    "Infrastructure": ["ID", "pills-infrastructure-tab"],
    "Running_filter": ["XPATH", "//button[contains(.,'Running')]"],
    "Message type": ["XPATH", "//button[contains(.,'Message type')]"],
    "Services": ["XPATH", "//*[@id='sapper']/main/div/div[2]/div/div/div[2]"],
    "Status": ["XPATH", "//button[contains(.,'Status')]"],
    "reset_filters": ["XPATH", "//button[contains(.,'Reset Filters')]"],
    "delete_alerts": ["XPATH", "//button[contains(.,'Delete Alerts')]"],
    "no_alerts": ["XPATH", '//*[@id="sapper"]/main/div/div[4]/h2'],
    "blogs_list": ["XPATH", '//*[@id="sapper"]/section[2]/div'],
}
